steps:
- name: 'g    else
      echo "Repository does not exist. Cloning."
      # Clone the repository as the current user.
      # This works now that the repository is public.
      git clone https://github.com/blackburnd/cloud_machine_repo.git /opt/cloud_machine_repo
    fi
    
    cd /opt/cloud_machine_repoud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'blackburnd@instance-20250825-143058'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    _REPO_URL="https://github.com/blackburnd/cloud_machine_repo.git"
    _REPO_DIR="/opt/cloud_machine_repo"
    
    if [ -d "$_REPO_DIR/.git" ]; then
      echo "Repository exists. Pulling latest changes."
      cd $_REPO_DIR
      git pull origin main
    else
      echo "Repository does not exist. Cloning."
      sudo mkdir -p /opt/cloud_machine_repo
      sudo chown -R blackburnd:blackburnd /opt/cloud_machine_repo
      cd /opt/cloud_machine_repo
      GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:blackburnd/cloud_machine_repo.git .
    fi
    
    cd $_REPO_DIR
    
    # Create a virtual environment and install dependencies
    if [ ! -d "venv" ]; then
      python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -r requirements.txt
    
    # Copy Nginx config
    sudo cp nginx/blackburnsystems.com /etc/nginx/sites-available/
    sudo ln -sf /etc/nginx/sites-available/blackburnsystems.com /etc/nginx/sites-enabled/
    
    # Make scripts executable
    chmod +x setup_ssl.sh
    chmod +x start.sh

    # Run SSL setup
    sudo ./setup_ssl.sh
    
    # Restart nginx to apply changes from certbot
    sudo systemctl restart nginx

    # Start the application
    ./start.sh 8000
options:
  logging: CLOUD_LOGGING_ONLY
