steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'blackburnd@instance-20250825-143058'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    set -e

    # Stop any running Nginx and kill all nginx processes to be safe
    sudo systemctl stop nginx || true
    sudo killall -9 nginx || true
    
    # Navigate to the repository directory or clone it
    if [ -d "/opt/cloud_machine_repo/.git" ]; then
      cd /opt/cloud_machine_repo
      git pull origin main
    else
      sudo git clone https://github.com/blackburnd/cloud_machine_repo.git /opt/cloud_machine_repo
      sudo chown -R blackburnd:blackburnd /opt/cloud_machine_repo
      cd /opt/cloud_machine_repo
    fi
    
    # Create a virtual environment and install dependencies
    if [ ! -d "venv" ]; then
      python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -r requirements.txt
    
    # Make scripts executable
    chmod +x setup_ssl.sh

    # Clean up any previous Nginx config
    sudo rm -f /etc/nginx/sites-enabled/blackburnsystems.com
    sudo rm -f /etc/nginx/sites-enabled/default
    sudo rm -f /etc/nginx/conf.d/default.conf

    # Copy the Nginx configuration
    sudo cp nginx/blackburnsystems.com /etc/nginx/sites-available/
    sudo ln -sf /etc/nginx/sites-available/blackburnsystems.com /etc/nginx/sites-enabled/

    # Validate the Nginx configuration before restarting
    sudo nginx -t

    # Install Cloud SQL Proxy for secure database connection
    if ! command -v cloud_sql_proxy &> /dev/null; then
      echo "Installing Cloud SQL Proxy..."
      wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      chmod +x cloud_sql_proxy
      sudo mv cloud_sql_proxy /usr/local/bin/
    fi

    # Start Cloud SQL Proxy as a systemd service
    sudo tee /etc/systemd/system/cloud-sql-proxy.service > /dev/null << 'EOF'
    [Unit]
    Description=Cloud SQL Proxy
    After=network.target

    [Service]
    Type=simple
    User=blackburnd
    ExecStart=/usr/local/bin/cloud_sql_proxy -instances=${_INSTANCE_CONNECTION_NAME}=tcp:5432
    Restart=always
    RestartSec=10

    [Install]
    WantedBy=multi-user.target
    EOF

    # Enable and start Cloud SQL Proxy
    sudo systemctl daemon-reload
    sudo systemctl enable cloud-sql-proxy
    sudo systemctl restart cloud-sql-proxy

    # Wait for proxy to start
    sleep 5

    # Create a systemd override file to set the environment variable
    # Use localhost since we're connecting through the proxy
    sudo mkdir -p /etc/systemd/system/portfolio.service.d
    sudo tee /etc/systemd/system/portfolio.service.d/override.conf > /dev/null << 'EOF'
    [Service]
    Environment=_DATABASE_URL=postgresql://${_PG_USER}:${_PG_PASS}@localhost:5432/${_PG_DB}
    EOF

    # Debug: Show what was written to the override file
    echo "=== Database configuration written ==="
    sudo cat /etc/systemd/system/portfolio.service.d/override.conf
    echo "======================================"

    # Set up the systemd service
    sudo cp portfolio.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable portfolio.service
    sudo systemctl restart portfolio.service

    # Start Nginx
    sudo systemctl start nginx
    sudo systemctl enable nginx

    # Wait for the application to start and check its status
    echo "Waiting for application to start..."
    sleep 10
    if sudo systemctl is-active --quiet portfolio.service; then
      echo "Application started successfully"
      echo "=== Service Status ==="
      sudo systemctl status portfolio.service --no-pager -l
      sudo systemctl status cloud-sql-proxy --no-pager -l
    else
      echo "Application failed to start. Showing logs:"
      sudo journalctl -u portfolio.service --no-pager -n 20
      echo "=== Cloud SQL Proxy logs ==="
      sudo journalctl -u cloud-sql-proxy --no-pager -n 10
      exit 1
    fi

substitutions:
  _PG_USER: 'postgres'
  _PG_PASS: '8JB6On1kTf6puF-'
  _PG_HOST: 'localhost'
  _PG_PORT: '5432'
  _PG_DB: 'daniel_portfolio'
  _INSTANCE_CONNECTION_NAME: 'impactful-study-470015-g5:us-central1:your-instance-name'

logsBucket: 'gs://impactful-study-470015-g5_cloudbuild_logs'
options:
  logging: GCS_ONLY
