steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'blackburnd@instance-20250825-143058'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    set -e

    # Stop any running Nginx and kill all nginx processes to be safe
    sudo systemctl stop nginx || true
    sudo killall -9 nginx || true
    
    # Navigate to the repository directory or clone it
    if [ -d "/opt/portfoliosite/.git" ]; then
      cd /opt/portfoliosite
      git pull origin main
    else
      sudo git clone https://github.com/blackburnd/portfoliosite.git /opt/portfoliosite
      sudo chown -R blackburnd:blackburnd /opt/portfoliosite
      cd /opt/portfoliosite
    fi
    
    # Clear Python cache files to prevent type definition conflicts
    find . -name "*.pyc" -delete 2>/dev/null || true
    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    
    # Create a virtual environment and install dependencies
    if [ ! -d "venv" ]; then
      python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -r requirements.txt
    
    # Make scripts executable
    chmod +x setup_ssl.sh

    # Validate GraphQL schema before deployment to catch type conflicts early
    echo "=== Validating GraphQL schema ==="
    source venv/bin/activate
    python3 validate_schema.py || exit 1

    # Clean up any previous Nginx config
    sudo rm -f /etc/nginx/sites-enabled/blackburnsystems.com
    sudo rm -f /etc/nginx/sites-enabled/default
    sudo rm -f /etc/nginx/conf.d/default.conf

    # Copy the Nginx configuration
    sudo cp nginx/blackburnsystems.com /etc/nginx/sites-available/
    sudo ln -sf /etc/nginx/sites-available/blackburnsystems.com /etc/nginx/sites-enabled/

    # Validate the Nginx configuration before restarting
    sudo nginx -t

    # Verify local assets exist
    echo "=== Checking local assets ==="
    if [ -d "app/assets/files" ]; then
        echo "✓ Assets directory exists"
        ls -la app/assets/files/
    else
        echo "✗ Assets directory not found"
    fi

    # Create the service file with environment variables substituted
    envsubst < portfolio.service > portfolio.service.tmp
    sudo mv portfolio.service.tmp portfolio.service.final

    # Set up the systemd service - force complete reset
    sudo systemctl stop portfolio.service || true
    sudo systemctl disable portfolio.service || true
    sudo rm -f /etc/systemd/system/portfolio.service
    sudo rm -rf /etc/systemd/system/portfolio.service.d
    sudo systemctl daemon-reload
    sudo cp portfolio.service.final /etc/systemd/system/portfolio.service
    sudo systemctl daemon-reload
    sudo systemctl enable portfolio.service
    sudo systemctl start portfolio.service

    # Start Nginx
    sudo systemctl start nginx
    sudo systemctl enable nginx

    # Wait for the application to start and check its status
    echo "Waiting for application to start..."
    sleep 10
    if sudo systemctl is-active --quiet portfolio.service; then
      echo "Application started successfully"
      echo "=== Service Status ==="
      sudo systemctl status portfolio.service --no-pager -l
      
      # Test local file access
      echo "=== Testing local file access ==="
      if curl -f http://localhost:8000/assets/files/ >/dev/null 2>&1; then
        echo "✓ Assets directory browsing works"
      else
        echo "✗ Assets directory browsing failed"
      fi
      
      if curl -f http://localhost:8000/assets/files/danielblackburn.pdf >/dev/null 2>&1; then
        echo "✓ Resume PDF accessible"
      else
        echo "✗ Resume PDF not accessible"
        echo "Available files:"
        curl -s http://localhost:8000/assets/files/ 2>/dev/null || echo "Directory listing failed"
      fi
      
    else
      echo "Application failed to start. Showing logs:"
      sudo journalctl -u portfolio.service --no-pager -n 20
      exit 1
    fi

substitutions:
  _PG_USER: ${_PG_USER}
  _PG_PASS: ${_PG_PASS}
  _PG_HOST: ${_PG_HOST}
  _PG_PORT: ${_PG_PORT}
  _PG_DB: ${_PG_DB}
  _GOOGLE_CLIENT_ID: ${_GOOGLE_CLIENT_ID}
  _GOOGLE_CLIENT_SECRET: ${_GOOGLE_CLIENT_SECRET}
  _GOOGLE_REDIRECT_URI: ${_GOOGLE_REDIRECT_URI}
  _ADMIN_USERNAME: ${_ADMIN_USERNAME}
  _ADMIN_PASSWORD: ${_ADMIN_PASSWORD}
  _SECRET_KEY: ${_SECRET_KEY}
  _AUTHORIZED_EMAILS: ${_AUTHORIZED_EMAILS}

logsBucket: 'gs://impactful-study-470015-g5_cloudbuild_logs'
options:
  logging: GCS_ONLY
