steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '--zone'
  'us-central1-c'
  - 'instance-20250825-143058' # e.g. us-central1-a
  - '--command'
  - |
    cd //home/blackburnd/sites/cloud_machine_repo
    git pull origin main
    ./start.sh 80
