steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'blackburnd@instance-20250825-143058'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    set -e

    # Stop any running Nginx and kill all nginx processes to be safe
    sudo systemctl stop nginx || true
    sudo killall -9 nginx || true
    
    if [ -d "/opt/cloud_machine_repo/.git" ]; then
      echo "Repository exists. Pulling latest changes."
      cd /opt/cloud_machine_repo
      git pull origin main
    else
      echo "Repository does not exist. Cloning."
      sudo mkdir -p /opt/cloud_machine_repo
      sudo chown -R blackburnd:blackburnd /opt/cloud_machine_repo
      git clone https://github.com/blackburnd/cloud_machine_repo.git /opt/cloud_machine_repo
    fi
    
    cd /opt/cloud_machine_repo
    
    # Create a virtual environment and install dependencies
    if [ ! -d "venv" ]; then
      python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -r requirements.txt
    
    # Make scripts executable
    chmod +x setup_ssl.sh

    # Clean up any previous Nginx config
    sudo rm -f /etc/nginx/sites-enabled/blackburnsystems.com
    sudo rm -f /etc/nginx/sites-enabled/default
    sudo rm -f /etc/nginx/conf.d/default.conf

    # Copy Nginx config FIRST
    sudo cp nginx/blackburnsystems.com /etc/nginx/sites-available/
    sudo ln -sf /etc/nginx/sites-available/blackburnsystems.com /etc/nginx/sites-enabled/

    # Run SSL setup to obtain and install certificates
    sudo ./setup_ssl.sh

    # Fetch the database URL from Secret Manager and create an environment file
    _SECRET_URL=$(gcloud secrets versions access latest --secret="_PORTFOLIO_DATABASE_URL")
    echo "_DATABASE_URL=${_SECRET_URL}" | sudo tee /etc/environment    
    # Set up the systemd service
    sudo cp portfolio.service /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable portfolio.service
    
    # Restart services
    sudo systemctl restart nginx
    sudo systemctl restart portfolio.service

logsBucket: 'gs://impactful-study-470015-g5_cloudbuild_logs'
options:
  logging: GCS_ONLY
