steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - '--zone'
  - 'us-central1-c'
  - 'instance-20250825-143058'
  - '--command'
  - |
    REPO_URL="https://github.com/blackburnd/cloud_machine_repo.git"
    REPO_DIR="/opt/cloud_machine_repo"
    
    if [ -d "$REPO_DIR/.git" ]; then
      echo "Repository exists. Pulling latest changes."
      cd $REPO_DIR
      git pull origin main
    else
      echo "Repository does not exist. Cloning."
      sudo mkdir -p /opt
      cd /opt
      sudo git clone $REPO_URL
      sudo chown -R $(whoami):$(whoami) $REPO_DIR
      cd $REPO_DIR
    fi
    
    cd $REPO_DIR
    
    # Create a virtual environment and install dependencies
    if [ ! -d "venv" ]; then
      python3 -m venv venv
    fi
    source venv/bin/activate
    pip install -r requirements.txt
    
    # Make scripts executable
    chmod +x setup_ssl.sh
    chmod +x start.sh

    # Run SSL setup
    sudo ./setup_ssl.sh

    # Copy Nginx config
    sudo cp nginx/blackburnsystems.com /etc/nginx/sites-available/
    sudo ln -sf /etc/nginx/sites-available/blackburnsystems.com /etc/nginx/sites-enabled/
    sudo systemctl restart nginx

    # Start the application
    ./start.sh 8000
